### ISSUE TITLE
GPL Ghostscript 9.07: Set UseCIEColor for UseDeviceIndependentColor to work properly

### ISSUE THREAD

**Issue by tAndreani** [zhangwei2015/IMonitor#7]
Hello,  

I am trying to reproduce the result of IMonitor using the data provided in the tool. I have this error and I think it is due by the fact that I cannot make proper plots (mostyl because the figures folder is empty apart these two pdf files: XHS_V_NT_composition.pdf and XHS_J_NT_composition.pdf). Question is: Have you ever had this problem? Basically the issue is ***GPL Ghostscript 9.07: Set UseCIEColor for UseDeviceIndependentColor to work properly***  and is happening at this step   
`bash XHS.statistics.graph.sh`    
```
XHS.merge_fq_fq2fa.sh start:  20-03-24.09:43:18
XHS.merge_fq_fq2fa.sh end:  20-03-24.09:43:23
XHS.blast.1.sh start:  20-03-24.09:43:23
XHS.blast.1.sh end:  20-03-24.09:43:34
XHS.blast.2.sh start:  20-03-24.09:43:34
XHS.blast.2.sh end:  20-03-24.09:43:44
XHS.blast.3.sh start:  20-03-24.09:43:44
XHS.blast.3.sh end:  20-03-24.09:43:54
XHS.structure.sh start:  20-03-24.09:43:54
XHS.structure.sh end:  20-03-24.09:43:55
XHS.statistics.graph.sh start:  20-03-24.09:43:55
Can't exec "/opt/blc/genome/biosoft/R/bin/Rscript": No such file or directory at /site/ne/home/i0439277/IMonitor/IMonitor-master/IMonitor/R_draw_figure.pl line 68.
Can't exec "/opt/blc/genome/biosoft/R/bin/Rscript": No such file or directory at /site/ne/home/i0439277/IMonitor/IMonitor-master/IMonitor/R_draw_figure.pl line 72.
Can't exec "/opt/blc/genome/biosoft/R/bin/Rscript": No such file or directory at /site/ne/home/i0439277/IMonitor/IMonitor-master/IMonitor/R_draw_figure.pl line 73.
Can't exec "/opt/blc/genome/biosoft/R/bin/Rscript": No such file or directory at /site/ne/home/i0439277/IMonitor/IMonitor-master/IMonitor/R_draw_figure.pl line 74.
Can't exec "/opt/blc/genome/biosoft/R/bin/Rscript": No such file or directory at /site/ne/home/i0439277/IMonitor/IMonitor-master/IMonitor/R_draw_figure.pl line 75.
Can't exec "/opt/blc/genome/biosoft/R/bin/Rscript": No such file or directory at /site/ne/home/i0439277/IMonitor/IMonitor-master/IMonitor/R_draw_figure.pl line 76.
Can't exec "/opt/blc/genome/biosoft/R/bin/Rscript": No such file or directory at /site/ne/home/i0439277/IMonitor/IMonitor-master/IMonitor/R_draw_figure.pl line 77.
Can't exec "/opt/blc/genome/biosoft/R/bin/Rscript": No such file or directory at /site/ne/home/i0439277/IMonitor/IMonitor-master/IMonitor/R_draw_figure.pl line 78.
Can't exec "/opt/blc/genome/biosoft/R/bin/Rscript": No such file or directory at /site/ne/home/i0439277/IMonitor/IMonitor-master/IMonitor/R_draw_figure.pl line 79.
Can't exec "/opt/blc/genome/biosoft/R/bin/Rscript": No such file or directory at /site/ne/home/i0439277/IMonitor/IMonitor-master/IMonitor/R_draw_figure.pl line 84.
Can't exec "/opt/blc/genome/biosoft/R/bin/Rscript": No such file or directory at /site/ne/home/i0439277/IMonitor/IMonitor-master/IMonitor/R_draw_figure.pl line 92.
GPL Ghostscript 9.07: Set UseCIEColor for UseDeviceIndependentColor to work properly.
GPL Ghostscript 9.07: Set UseCIEColor for UseDeviceIndependentColor to work properly.
Can't exec "/opt/blc/genome/biosoft/R/bin/Rscript": No such file or directory at /site/ne/home/i0439277/IMonitor/IMonitor-master/IMonitor/R_draw_figure.pl line 108.
XHS.statistics.graph.sh end:  20-03-24.09:44:01
XHS.rm.intermediate.file.sh start:  20-03-24.09:44:01
XHS.rm.intermediate.file.sh end:  20-03-24.09:44:01
```

have you ever incountered this issue? Could you give me some advice in what I have to change? Alos it seems that some imput for R_draw_figure.pl cannot be found.

Thank you in advance for any adivce.

**Comment by tAndreani** [comment]
solved installing https://anaconda.org/conda-forge/ghostscript

**Comment by zhangwei2015** [comment]
Dear Tommaso,

The problem is about the R you provided. You have to check that the directory "/opt/blc/genome/biosoft/R/bin/Rscript" exist and work.

Best Regards!
Wei

发件人: Tommaso Andreani <notifications@github.com>
发送时间: 2020年3月24日 22:05
收件人: zhangwei2015/IMonitor <IMonitor@noreply.github.com>
抄送: Subscribed <subscribed@noreply.github.com>
主题: [zhangwei2015/IMonitor] GPL Ghostscript 9.07: Set UseCIEColor for UseDeviceIndependentColor to work properly (#7)


Hello,

I am trying to reproduce the result of IMonitor using the data provided in the tool. I have this error and I think it is due by the fact that I cannot make proper plots (mostyl because the figures folder is empty apart these two pdf files: XHS_V_NT_composition.pdf and XHS_J_NT_composition.pdf). Question is: Have you ever had this problem? Basically the issue is GPL Ghostscript 9.07: Set UseCIEColor for UseDeviceIndependentColor to work properly

XHS.merge_fq_fq2fa.sh start:  20-03-24.09:43:18

XHS.merge_fq_fq2fa.sh end:  20-03-24.09:43:23

XHS.blast.1.sh start:  20-03-24.09:43:23

XHS.blast.1.sh end:  20-03-24.09:43:34

XHS.blast.2.sh start:  20-03-24.09:43:34

XHS.blast.2.sh end:  20-03-24.09:43:44

XHS.blast.3.sh start:  20-03-24.09:43:44

XHS.blast.3.sh end:  20-03-24.09:43:54

XHS.structure.sh start:  20-03-24.09:43:54

XHS.structure.sh end:  20-03-24.09:43:55

XHS.statistics.graph.sh start:  20-03-24.09:43:55

Can't exec "/opt/blc/genome/biosoft/R/bin/Rscript": No such file or directory at /site/ne/home/i0439277/IMonitor/IMonitor-master/IMonitor/R_draw_figure.pl line 68.

Can't exec "/opt/blc/genome/biosoft/R/bin/Rscript": No such file or directory at /site/ne/home/i0439277/IMonitor/IMonitor-master/IMonitor/R_draw_figure.pl line 72.

Can't exec "/opt/blc/genome/biosoft/R/bin/Rscript": No such file or directory at /site/ne/home/i0439277/IMonitor/IMonitor-master/IMonitor/R_draw_figure.pl line 73.

Can't exec "/opt/blc/genome/biosoft/R/bin/Rscript": No such file or directory at /site/ne/home/i0439277/IMonitor/IMonitor-master/IMonitor/R_draw_figure.pl line 74.

Can't exec "/opt/blc/genome/biosoft/R/bin/Rscript": No such file or directory at /site/ne/home/i0439277/IMonitor/IMonitor-master/IMonitor/R_draw_figure.pl line 75.

Can't exec "/opt/blc/genome/biosoft/R/bin/Rscript": No such file or directory at /site/ne/home/i0439277/IMonitor/IMonitor-master/IMonitor/R_draw_figure.pl line 76.

Can't exec "/opt/blc/genome/biosoft/R/bin/Rscript": No such file or directory at /site/ne/home/i0439277/IMonitor/IMonitor-master/IMonitor/R_draw_figure.pl line 77.

Can't exec "/opt/blc/genome/biosoft/R/bin/Rscript": No such file or directory at /site/ne/home/i0439277/IMonitor/IMonitor-master/IMonitor/R_draw_figure.pl line 78.

Can't exec "/opt/blc/genome/biosoft/R/bin/Rscript": No such file or directory at /site/ne/home/i0439277/IMonitor/IMonitor-master/IMonitor/R_draw_figure.pl line 79.

Can't exec "/opt/blc/genome/biosoft/R/bin/Rscript": No such file or directory at /site/ne/home/i0439277/IMonitor/IMonitor-master/IMonitor/R_draw_figure.pl line 84.

Can't exec "/opt/blc/genome/biosoft/R/bin/Rscript": No such file or directory at /site/ne/home/i0439277/IMonitor/IMonitor-master/IMonitor/R_draw_figure.pl line 92.

GPL Ghostscript 9.07: Set UseCIEColor for UseDeviceIndependentColor to work properly.

GPL Ghostscript 9.07: Set UseCIEColor for UseDeviceIndependentColor to work properly.

Can't exec "/opt/blc/genome/biosoft/R/bin/Rscript": No such file or directory at /site/ne/home/i0439277/IMonitor/IMonitor-master/IMonitor/R_draw_figure.pl line 108.

XHS.statistics.graph.sh end:  20-03-24.09:44:01

XHS.rm.intermediate.file.sh start:  20-03-24.09:44:01

XHS.rm.intermediate.file.sh end:  20-03-24.09:44:01

have you ever incountered this issue? Could you give me some advice in what I have to change? Alos it seems that some imput for R_draw_figure.pl cannot be found.

Thank you in advance for any adivce.

**Comment by tAndreani** [comment]
Thank you for the reply and thank for the nice tool! I have corrected the path and now it works.

Can I ask you some question related to the IGKL and IGH chain? For IGKL i have run without -d and with the -d paramenter but I do not have the structure of it, is this normal? Is this because the data is from T-cells only?

For IGH there is the final structure but the final plot does not have several images that are in the TCR example.. I in the **overall plot** below there are only these info, is this normal?

<img width="575" alt="IMonitor_IGH" src="https://user-images.githubusercontent.com/6462162/77523314-dadf6280-6e85-11ea-93ef-53c6641e19a6.PNG">

Thank you very much for any reply!

**Comment by zhangwei2015** [comment]
Yes, if you use TCR data for IGH or IGKL analysis, most of sequences cannot find the V and J genes, so there will be some problem.
I guess:
For IGKL, no sequence(read) find the V and J genes, so the structure didn’t appear;
For IGH, there might be several sequences finding the V/J genes(according to your figure of PDF), and some statistics were missed, so some figures were missed.

Each time, you could check two files in Result/:

1.     *_bascial_filter_stat.txt     :   record all basic data processing. If the data has some problem, you can find the reason from it.

2.     *_further.stat.txt     :   statistics of repertoire from the final effective data


Best Regards!
Wei
发件人: Tommaso Andreani <notifications@github.com>
发送时间: 2020年3月25日 17:48
收件人: zhangwei2015/IMonitor <IMonitor@noreply.github.com>
抄送: 张伟(Wei Zhang) <zhangwei3@genomics.cn>; Comment <comment@noreply.github.com>
主题: Re: [zhangwei2015/IMonitor] GPL Ghostscript 9.07: Set UseCIEColor for UseDeviceIndependentColor to work properly (#7)


Thank you for the reply and thank for the nice tool! I have corrected the path and now it works.

Can I ask you some question related to the IGKL and IGH chain? For IGKL i have run without -d and with the -d paramenter but I do not have the structure of it, is this normal? Is this because the data is from T-cells only?

For IGH there is the final structure but the final plot does not have several images that are in the TCR example.. I have the pdf below only, is this normal?

[IMonitor_IGH]<https://user-images.githubusercontent.com/6462162/77523314-dadf6280-6e85-11ea-93ef-53c6641e19a6.PNG>

Thank you very much for any reply!

**Comment by tAndreani** [comment]
Yes I mean I have used the fastq files that are provided in the IMonitor folder to make the test. I was wondering if those fastq files included B cells. T-cells are included for sure because that analysis works perfectly but I am not sure is the same for the B-cells IGH and IGKL analysis..

**Comment by zhangwei2015** [comment]
In the Test of IMonitor, it only includes the TCR beta data.

发件人: Tommaso Andreani <notifications@github.com>
发送时间: 2020年3月25日 21:20
收件人: zhangwei2015/IMonitor <IMonitor@noreply.github.com>
抄送: 张伟(Wei Zhang) <zhangwei3@genomics.cn>; Comment <comment@noreply.github.com>
主题: Re: [zhangwei2015/IMonitor] GPL Ghostscript 9.07: Set UseCIEColor for UseDeviceIndependentColor to work properly (#7)


Yes I mean I have used the fastq files that are provided in the IMonitor folder to make the test. I was wondering if those fastq files included B cells. T-cells are included for sure because that analysis works perfectly but I am not sure is the same for the B-cells IGH and IGKL analysis..

**Comment by tAndreani** [comment]
ah ok thank you. Last question, if I have paired end fastq files but I do not have the adapters how can I run IMonitor? Should I extract them? How did you obtain the adapters in your example test: data/1.adapter.list.gz data/2.adapter.list.gz?

**Comment by zhangwei2015** [comment]
Actually, you don't need the adapter files  because the program will remove the extra bases(maybe adapter sequence) when paired end reads are merged. you can just use an empty file instead.

Best,
Wei



发自我的小米手机
在 Tommaso Andreani <notifications@github.com>，2020年3月25日 下午9:40写道：

ah ok thank you. Last question, if I have paired end fastq files but I do not have the adapters how can I run IMonitor? Should I extract them? How did you obtain the adapters in your example test: data/1.adapter.list.gz data/2.adapter.list.gz?

**Comment by tAndreani** [comment]
Ah ok thank you for the info!

I have tried to use my own RNA-seq data and I have provided the fastq files, since i do not have any output running `Excute_all.sh` ,  I started from the 1st command `bash myRNA.merge_fq_fq2fa.sh` but I have an error:  

```
myRNA.merge_fq_fq2fa.sh start:  20-03-25.12:02:00
Illegal division by zero at /site/ne/home/i0439277/IMonitor/IMonitor-master/IMonitor/Filter_adapter_lowqual_N.pl line 220.
Illegal division by zero at /site/ne/home/i0439277/IMonitor/IMonitor-master/IMonitor/Merge_filter_fqtofa.pl line 155.
Use of uninitialized value $all in division (/) at /site/ne/home/i0439277/IMonitor/IMonitor-master/IMonitor/Split_fq_into_part.pl line 19.
myRNA.merge_fq_fq2fa.sh end:  20-03-25.12:18:05
````

in this datasets the reads are 300 in length so I have adjusted the -K parameter. Do you have any idea of what could be this error?

**Comment by zhangwei2015** [comment]
I guess:
It seems like all reads were filtered by low quality.  Please check the parameter -v (quality system):  the sequencing quality is calculated by ASCII-64 or ASCII-33, so -v is given 64 or 33. You should check your data.

Best,
Wei

发件人: Tommaso Andreani <notifications@github.com>
发送时间: 2020年3月26日 0:31
收件人: zhangwei2015/IMonitor <IMonitor@noreply.github.com>
抄送: 张伟(Wei Zhang) <zhangwei3@genomics.cn>; Comment <comment@noreply.github.com>
主题: Re: [zhangwei2015/IMonitor] GPL Ghostscript 9.07: Set UseCIEColor for UseDeviceIndependentColor to work properly (#7)


Ah ok thank you for the info!

I have tried to use my own RNA-seq data and I have provided the fastq files, since i do not have any output running Excute_all.sh , I started from the 1st command bash myRNA.merge_fq_fq2fa.sh but I have an error:

myRNA.merge_fq_fq2fa.sh start:  20-03-25.12:02:00

Illegal division by zero at /site/ne/home/i0439277/IMonitor/IMonitor-master/IMonitor/Filter_adapter_lowqual_N.pl line 220.

Illegal division by zero at /site/ne/home/i0439277/IMonitor/IMonitor-master/IMonitor/Merge_filter_fqtofa.pl line 155.

Use of uninitialized value $all in division (/) at /site/ne/home/i0439277/IMonitor/IMonitor-master/IMonitor/Split_fq_into_part.pl line 19.

myRNA.merge_fq_fq2fa.sh end:  20-03-25.12:18:05

in this datasets the reads are 300 in length so I have adjusted the -K parameter. Do you have any idea of what could be this error?
